### ISSUE TITLE
 No module named 'app'

### ISSUE THREAD

**Issue by KrunchMuffin** [alexvanzyl/fastapi-simple-app-example#1]
Hi Alex,

Love this tutorial. Best one for FAPI yet.

No idea why I am getting this error, but wondering if you could shed some light?

```
  File "alembic\env.py", line 17, in <module>
  from app.db import Base  # noqa
  ModuleNotFoundError: No module named 'app'
```

![image](https://user-images.githubusercontent.com/1037197/90820761-e2ede200-e2ff-11ea-9dce-09c98117bfc7.png)

**Comment by KrunchMuffin** [comment]
with some sleuthing I added this in env.py
`sys.path = ["", ".."] + sys.path[1:]`
and all is good now.

**Comment by alexvanzyl** [comment]
@KrunchMuffin happy you enjoyed the article, hope it was useful! I have run into this before. What I resorted to doing is remove the virtual environment completely then installing everything again with `poetry install`. After that doing `poetry run alembic <command>` should work as usual.
